# Generated by Django 4.2.30 on 2026-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_task_assigned',
            field=models.BooleanField(default=True, verbose_name='แจ้งเตือนมอบหมายงาน'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_task_error',
            field=models.BooleanField(default=True, verbose_name='แจ้งเตือนรายงานข้อผิดพลาด'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_task_overdue',
            field=models.BooleanField(default=True, verbose_name='แจ้งเตือนงานเกินกำหนด'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_task_problem',
            field=models.BooleanField(default=True, verbose_name='แจ้งเตือนรายงานปัญหา'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_task_rescheduled',
            field=models.BooleanField(default=True, verbose_name='แจ้งเตือนเปลี่ยนเวลางาน'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_task_starting',
            field=models.BooleanField(default=True, verbose_name='แจ้งเตือนงานกำลังจะเริ่ม'),
        ),
    ]
