# Generated by Django 4.2.30 on 2026-08-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile_notify_task_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, help_text='รหัสสำหรับเข้าสู่ระบบ (ตั้งเอง)', max_length=50, null=True, unique=True, verbose_name='รหัสผู้ใช้'),
        ),
    ]
