# Generated by Django 4.2.30 on 2026-08-27 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่องาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('category', models.CharField(choices=[('production', 'การผลิต'), ('warehouse', 'คลังสินค้า'), ('delivery', 'จัดส่ง'), ('cleaning', 'ทำความสะอาด'), ('maintenance', 'ซ่อมบำรุง'), ('admin', 'งานธุรการ'), ('other', 'อื่นๆ')], default='other', max_length=20, verbose_name='หมวดหมู่')),
                ('priority', models.IntegerField(choices=[(1, 'ต่ำ'), (2, 'ปานกลาง'), (3, 'สูง'), (4, 'เร่งด่วน'), (5, 'วิกฤต')], default=2, verbose_name='ความสำคัญ')),
                ('status', models.CharField(choices=[('scheduled', 'กำหนดไว้'), ('ready', 'พร้อมรับงาน'), ('accepted', 'รับงานแล้ว'), ('in_progress', 'กำลังทำ'), ('completed', 'เสร็จแล้ว'), ('problem', 'มีปัญหา'), ('error', 'เกิดข้อผิดพลาด'), ('postponed', 'เลื่อน'), ('cancelled', 'ยกเลิก')], default='scheduled', max_length=20, verbose_name='สถานะ')),
                ('prepare_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเตรียมงาน')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่มงาน')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='กำหนดส่ง')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเสร็จ')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='เวลาที่คาดว่าจะใช้ (นาที)')),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='เวลาที่ใช้จริง (นาที)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='สถานที่')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='งานประจำ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.team', verbose_name='ทีมที่รับผิดชอบ')),
            ],
            options={
                'verbose_name': 'งาน',
                'verbose_name_plural': 'งาน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('problem', 'ปัญหา'), ('error', 'ข้อผิดพลาด'), ('delay', 'ความล่าช้า'), ('quality', 'คุณภาพ'), ('safety', 'ความปลอดภัย'), ('other', 'อื่นๆ')], max_length=20, verbose_name='ประเภทรายงาน')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('resolution', models.TextField(blank=True, verbose_name='วิธีแก้ไข')),
                ('resolved', models.BooleanField(default=False, verbose_name='แก้ไขแล้ว')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาแก้ไข')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reports', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รายงาน')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tasks.task', verbose_name='งาน')),
            ],
            options={
                'verbose_name': 'รายงานปัญหา',
                'verbose_name_plural': 'รายงานปัญหา',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'สร้างงาน'), ('assigned', 'มอบหมายงาน'), ('accepted', 'รับงาน'), ('started', 'เริ่มงาน'), ('completed', 'เสร็จงาน'), ('problem_reported', 'รายงานปัญหา'), ('error_reported', 'รายงานข้อผิดพลาด'), ('postponed', 'เลื่อนงาน'), ('cancelled', 'ยกเลิกงาน'), ('status_changed', 'เปลี่ยนสถานะ'), ('note_added', 'เพิ่มหมายเหตุ')], max_length=20, verbose_name='รายการ')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='สถานะเดิม')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='สถานะใหม่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task', verbose_name='งาน')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ทำรายการ')),
            ],
            options={
                'verbose_name': 'ประวัติงาน',
                'verbose_name_plural': 'ประวัติงาน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tasks.task', verbose_name='งานที่ต้องเสร็จก่อน')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='tasks.task', verbose_name='งานที่รอ')),
            ],
            options={
                'verbose_name': 'ความสัมพันธ์งาน',
                'verbose_name_plural': 'ความสัมพันธ์งาน',
                'unique_together': {('task', 'depends_on')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลารับงาน')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่มทำ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเสร็จ')),
                ('is_primary', models.BooleanField(default=False, verbose_name='ผู้รับผิดชอบหลัก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='มอบหมายโดย')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='มอบหมายให้')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='งาน')),
            ],
            options={
                'verbose_name': 'การมอบหมายงาน',
                'verbose_name_plural': 'การมอบหมายงาน',
                'unique_together': {('task', 'assigned_to')},
            },
        ),
    ]
