# Generated by Django 4.2.30 on 2026-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(blank=True, help_text='วันที่กำหนดให้ทำงาน ใช้สำหรับแสดงใน today/tomorrow view', null=True, verbose_name='วันที่งาน'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'ต่ำ'), (2, 'ปกติ'), (3, 'สูง'), (4, 'เร่งด่วน')], default=2, verbose_name='ความสำคัญ'),
        ),
    ]
