# Generated by Django 4.2.30 on 2026-08-27 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_task_date_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_date', 'start_at', 'queue_position'], 'verbose_name': 'งาน', 'verbose_name_plural': 'งาน'},
        ),
        migrations.AddField(
            model_name='task',
            name='queue_position',
            field=models.PositiveIntegerField(default=0, help_text='ตำแหน่งเรียงลำดับงานในแต่ละวัน', verbose_name='ตำแหน่งในคิว'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_id',
            field=models.CharField(blank=True, help_text='รหัสสำหรับป้องกัน duplicate recurrence instance', max_length=100, verbose_name='รหัส recurrence instance'),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อแม่แบบ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('category', models.CharField(choices=[('production', 'การผลิต'), ('warehouse', 'คลังสินค้า'), ('delivery', 'จัดส่ง'), ('cleaning', 'ทำความสะอาด'), ('maintenance', 'ซ่อมบำรุง'), ('admin', 'งานธุรการ'), ('other', 'อื่นๆ')], default='other', max_length=20, verbose_name='หมวดหมู่')),
                ('priority', models.IntegerField(choices=[(1, 'ต่ำ'), (2, 'ปกติ'), (3, 'สูง'), (4, 'เร่งด่วน')], default=2, verbose_name='ความสำคัญ')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='เวลาที่คาดว่าจะใช้ (นาที)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='สถานที่')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('default_prepare_minutes_before', models.PositiveIntegerField(default=0, help_text='จำนวนนาทีก่อน start_at ที่ควรเริ่มเตรียมงาน', verbose_name='เตรียมงานล่วงหน้า (นาที)')),
                ('default_duration_minutes', models.PositiveIntegerField(default=60, help_text='ระยะเวลาที่คาดว่าจะใช้ทำงาน', verbose_name='ระยะเวลาทำงาน (นาที)')),
                ('recurrence_type', models.CharField(choices=[('none', 'ไม่ประจำ'), ('daily', 'ทุกวัน'), ('weekdays', 'จันทร์-ศุกร์'), ('weekly', 'ทุกสัปดาห์')], default='none', max_length=20, verbose_name='ประเภทการประจำ')),
                ('recurrence_time', models.TimeField(blank=True, help_text='เวลาเริ่มงานสำหรับงานที่ทำประจำ', null=True, verbose_name='เวลาเริ่มงานประจำ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('default_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='accounts.team', verbose_name='ทีมเริ่มต้น')),
            ],
            options={
                'verbose_name': 'แม่แบบงาน',
                'verbose_name_plural': 'แม่แบบงาน',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='tasks.tasktemplate', verbose_name='แม่แบบที่ใช้สร้าง'),
        ),
    ]
