# Generated by Django 4.2.30 on 2026-08-27 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_options_task_queue_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่รับงาน'),
        ),
        migrations.AddField(
            model_name='task',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับงาน'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_open',
            field=models.BooleanField(default=False, help_text='True = งานเปิดให้ใครก็ได้มาแย่งรับ, False = มอบหมายเฉพาะคน', verbose_name='งานเปิดรับ'),
        ),
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ค่าตอบแทนสำหรับงานนี้ (บาท)', max_digits=10, verbose_name='ค่าตอบแทน (฿)'),
        ),
    ]
