# Generated by Django 4.2.30 on 2026-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_open_task_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='is_open',
            field=models.BooleanField(default=False, help_text='True = สร้างเป็นงานเปิดให้แย่ง, False = มอบหมายเฉพาะคน', verbose_name='งานเปิดรับ'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ค่าตอบแทนสำหรับงานนี้ (บาท)', max_digits=10, verbose_name='ค่าตอบแทน (฿)'),
        ),
    ]
