# Generated by Django 4.2.30 on 2026-08-27 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'ได้รับมอบหมายงาน'), ('task_completed', 'งานเสร็จแล้ว'), ('task_overdue', 'งานเกินกำหนด'), ('task_updated', 'งานถูกอัพเดท'), ('problem_reported', 'มีการรายงานปัญหา'), ('system', 'ระบบ')], max_length=20, verbose_name='ประเภท')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาอ่าน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task', verbose_name='งานที่เกี่ยวข้อง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'แจ้งเตือน',
                'verbose_name_plural': 'แจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
    ]
