# Generated by Django 4.2.30 on 2026-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'ได้รับมอบหมายงาน'), ('task_starting', 'งานกำลังจะเริ่ม'), ('task_completed', 'งานเสร็จแล้ว'), ('task_overdue', 'งานเกินกำหนด'), ('task_rescheduled', 'เปลี่ยนเวลางาน'), ('task_postponed', 'เลื่อนงาน'), ('task_problem', 'รายงานปัญหา'), ('task_error', 'รายงานข้อผิดพลาด'), ('task_updated', 'งานถูกอัพเดท'), ('problem_reported', 'มีการรายงานปัญหา'), ('system', 'ระบบ')], max_length=20, verbose_name='ประเภท'),
        ),
    ]
